const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
require('node:fs').mkdirSync('audit-captures',{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:800}});
 const errors=[];const requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.route('**/*gstatic.com/**',r=>r.abort());
 await page.goto(process.env.TEST_URL || 'http://localhost:4173/',{waitUntil:'networkidle'});
 assert(!requests.some(u=>u.endsWith('.glb')),'Homepage must not download model');
 console.log('HOME', {modelRequests:0,images:requests.filter(u=>/images/.test(u)).length});
 const start=Date.now();await page.getByRole('button',{name:'进入空间漫游',exact:true}).click();
 await page.locator('.scene-welcome:not(.is-ready)').waitFor();
 console.log('PREVIEW_MS',Date.now()-start);
 await page.screenshot({path:'audit-captures/loading-after.png'});
 await page.locator('.scene-welcome.is-ready').waitFor({state:'attached',timeout:60000});
 console.log('READY_MS',Date.now()-start);
 await page.waitForTimeout(650);await page.screenshot({path:'audit-captures/scene-after.png'});
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');
 await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('[role=dialog]')));
 await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'');
 assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'进入空间漫游');
 const repeat=Date.now();await page.getByRole('button',{name:'进入空间漫游',exact:true}).click();
 await page.locator('.scene-welcome.is-ready').waitFor({state:'attached',timeout:60000});
 console.log('REOPEN_MS',Date.now()-repeat,'MODEL_REQUESTS',requests.filter(u=>u.endsWith('.glb')).length);
 assert.equal(requests.filter(u=>u.endsWith('.glb')).length,1);
 await page.evaluate(()=>document.querySelector('canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));
 await page.getByRole('button',{name:'重新加载',exact:true}).waitFor();
 await page.getByRole('button',{name:'重新加载',exact:true}).click();
 await page.locator('.scene-welcome.is-ready').waitFor({state:'attached',timeout:60000});
 console.log('CONTEXT_RECOVERY','passed','ERRORS',errors);
 assert.equal(errors.length,0);
 await page.close();
 const bad=await browser.newPage();
 let block=true; await bad.route('**/draco/draco_decoder.wasm',r=>block?r.abort():r.continue());
 await bad.goto(process.env.TEST_URL || 'http://localhost:4173/');await bad.getByRole('button',{name:'进入空间漫游',exact:true}).click();
 await bad.getByRole('button',{name:'重新加载',exact:true}).waitFor({timeout:20000});
 console.log('FAILED_DECODER','actionable error shown');
 await bad.screenshot({path:'audit-captures/error-after.png'});
 block=false;await bad.getByRole('button',{name:'重新加载',exact:true}).click();
 await bad.locator('.scene-welcome.is-ready').waitFor({state:'attached',timeout:60000});
 console.log('FAILED_DECODER_RETRY','passed');
 await bad.close();
 const unavailable=await browser.newPage();
 await unavailable.addInitScript(()=>{
   const original=HTMLCanvasElement.prototype.getContext;
   HTMLCanvasElement.prototype.getContext=function(type,...args){ return type==='webgl2' ? null : original.call(this,type,...args); };
 });
 await unavailable.goto(process.env.TEST_URL || 'http://localhost:4173/');
 await unavailable.getByRole('button',{name:'进入空间漫游',exact:true}).click();
 await unavailable.getByRole('button',{name:'重新加载',exact:true}).waitFor();
 await unavailable.getByRole('button',{name:'返回浏览图文',exact:true}).click();
 await unavailable.getByRole('dialog').waitFor({state:'detached'});
 console.log('UNAVAILABLE_WEBGL','recoverable fallback passed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

